package es.us.dad.WAIT.entities;

public class Device {

	/**
	 * Unique identifier of the device in the system. This is the primary key. Being
	 * autogenerated, debugging problems can occur when a device is removed, since
	 * this identifier cannot be reused.
	 */
	private Integer idDevice;

	/**
	 * To get around the above problem, this property is defined which is also an
	 * identifier for the device. However, since it is not auto-incremental (but is
	 * unique), it can be reused in case the original sensor with that value is
	 * deleted.
	 */
	private String deviceSerialId;

	/**
	 * Name assigned to the device
	 */
	private String name;

	/**
	 * MQTT channel associated with this device and through which the necessary MQTT
	 * messages will be shared between the server and said device.
	 */

	/**
	 * Identifier of the group to which the device belongs
	 */

	/**
	 * Timestamp of when the last reading was taken from a sensor associated with
	 * this device.
	 */
	private Long lastTimestampSensorModified;

	/**
	 * Timestamp of when the last status was set to a actuator associated with this
	 * device.
	 */
	private Long lastTimestampActuatorModified;

	public Device() {
		super();
	}

	public Device(String deviceSerialId, String name,
			Long lastTimestampSensorModified, Long lastTimestampActuatorModified) {
		super();
		this.deviceSerialId = deviceSerialId;
		this.name = name;
		this.lastTimestampSensorModified = lastTimestampSensorModified;
		this.lastTimestampActuatorModified = lastTimestampActuatorModified;
	}

	public Device(Integer idDevice, String deviceSerialId, String name,
			Long lastTimestampSensorModified, Long lastTimestampActuatorModified) {
		super();
		this.idDevice = idDevice;
		this.deviceSerialId = deviceSerialId;
		this.name = name;
		this.lastTimestampSensorModified = lastTimestampSensorModified;
		this.lastTimestampActuatorModified = lastTimestampActuatorModified;
	}

	public Integer getIdDevice() {
		return idDevice;
	}

	public void setIdDevice(Integer idDevice) {
		this.idDevice = idDevice;
	}

	public String getDeviceSerialId() {
		return deviceSerialId;
	}

	public void setDeviceSerialId(String deviceSerialId) {
		this.deviceSerialId = deviceSerialId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public Long getLastTimestampSensorModified() {
		return lastTimestampSensorModified;
	}

	public void setLastTimestampSensorModified(Long lastTimestampSensorModified) {
		this.lastTimestampSensorModified = lastTimestampSensorModified;
	}

	public Long getLastTimestampActuatorModified() {
		return lastTimestampActuatorModified;
	}

	public void setLastTimestampActuatorModified(Long lastTimestampActuatorModified) {
		this.lastTimestampActuatorModified = lastTimestampActuatorModified;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((deviceSerialId == null) ? 0 : deviceSerialId.hashCode());
		result = prime * result + ((idDevice == null) ? 0 : idDevice.hashCode());
		result = prime * result
				+ ((lastTimestampActuatorModified == null) ? 0 : lastTimestampActuatorModified.hashCode());
		result = prime * result + ((lastTimestampSensorModified == null) ? 0 : lastTimestampSensorModified.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Device other = (Device) obj;
		if (deviceSerialId == null) {
			if (other.deviceSerialId != null)
				return false;
		} else if (!deviceSerialId.equals(other.deviceSerialId))
			return false;
		if (idDevice == null) {
			if (other.idDevice != null)
				return false;
		} else if (!idDevice.equals(other.idDevice))
			return false;
		if (lastTimestampActuatorModified == null) {
			if (other.lastTimestampActuatorModified != null)
				return false;
		} else if (!lastTimestampActuatorModified.equals(other.lastTimestampActuatorModified))
			return false;
		if (lastTimestampSensorModified == null) {
			if (other.lastTimestampSensorModified != null)
				return false;
		} else if (!lastTimestampSensorModified.equals(other.lastTimestampSensorModified))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Device [idDevice=" + idDevice + ", deviceSerialId=" + deviceSerialId + ", name=" + name
				+  ", lastTimestampSensorModified="
				+ lastTimestampSensorModified + ", lastTimestampActuatorModified=" + lastTimestampActuatorModified
				+ "]";
	}

	public boolean equalsWithNoIdConsidered(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Device other = (Device) obj;
		if (deviceSerialId == null) {
			if (other.deviceSerialId != null)
				return false;
		} else if (!deviceSerialId.equals(other.deviceSerialId))
			return false;
		if (lastTimestampActuatorModified == null) {
			if (other.lastTimestampActuatorModified != null)
				return false;
		} else if (!lastTimestampActuatorModified.equals(other.lastTimestampActuatorModified))
			return false;
		if (lastTimestampSensorModified == null) {
			if (other.lastTimestampSensorModified != null)
				return false;
		} else if (!lastTimestampSensorModified.equals(other.lastTimestampSensorModified))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

}
